### ISSUE TITLE
Fails to build with `ghc 9.2.1` and `base-4.16.0.0`

### ISSUE THREAD

**Issue by odiferousmint** [doma-engineering/passveil#2]
```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: passveil-0.1.0.0 (user goal)
[__1] next goal: base (dependency of passveil)
[__1] rejecting: base-4.16.0.0/installed-4.16.0.0 (conflict: passveil =>
base^>=4.14.0.0)
[__1] skipping: base-4.16.0.0, base-4.15.1.0, base-4.15.0.0 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '^>=4.14.0.0' from 'passveil')
[__1] rejecting: base-4.14.3.0, base-4.14.2.0, base-4.14.1.0, base-4.14.0.0,
base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: base, passveil)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, passveil
```

I manually had to change the `passveil.cabal` file and I ran into an issue related to `hexstring`. Patching it as per https://github.com/solatis/haskell-hexstring/issues/3#issuecomment-878296984 made it successfully compile, but then I ran into another issue and this time it was something in `passveil`'s codebase. I have to go to sleep, but I may report back with what the issue was.

I am using `ghc 9.2.1` and `cabal-install 3.6.2.0`. I would say that everything is the latest, thanks to `ghcup`. I had no idea `cabal` would not fetch those versions of the dependencies though and all that.

**Comment by cognivore** [comment]
Oh wow, thank you for the interest in the repo! No idea how I missed it. My guess is that raichoo et al have already patched this stuff in the darcs repo. This is a fork we use in doma.dev, and since we don't really use Haskell, we have no problem using old versions of the toolchain.

But there's a bunch of annoying things about passveil that we plan to fix, so, perhaps, around Christmas this year, I'll do a maintenance pass on this repo. 

Thanks again for reporting!

**Comment by odiferousmint** [comment]
No worries! :)

**Comment by cognivore** [comment]
@odiferousmint two years later...
